<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Закажите консультацию — мы позвоним вам' => 'Order a consultation - we will call soon',
    'Подтвердите согласие на обработку персональных данных' => 'Confirm your consent to the processing of personal data',
    'Я согласен на обработку персональных данных' => 'I agree to the processing of personal data',
    'заказать тренинг' => 'Order a training',
    'с выгодным предложением по тренировкам' => 'with a profitable offer for training',
    'Ваше имя' => 'Your name',
    'Персональный тренинг' => 'Personal training',
    'Телефон' => 'Phone',
    'Электронная почта' => 'Email',
];
